theme: jekyll-theme-minimal
title: Adam Cadien
description: Engineering Leader | Robotics & Autonomous Systems
linkedin_url: https://www.linkedin.com/in/adam-cadien-a3969620/
show_downloads: true  # Set to true if you want to show PDF download link
pdf_resume: /assets/resumeCadien2025.pdf
